### ISSUE TITLE
单元测试类文件 SortTest.java 中多了一个字符 `

### ISSUE THREAD

**Issue by fcbhank** [hcsp/sort-algorithm-practice#1]
@blindpirate 
[SortTest.java](https://github.com/fcbhank/sort-algorithm-practice/blob/master/src/test/java/com/github/hcsp/algorithm/SortTest.java/#L22) 多了一个字符' ` '

**Comment by blindpirate** [comment]
多谢提醒！这个代码是自动化工具生成的，所以没有注意到。

Fixed in https://github.com/hcsp/sort-algorithm-practice/commit/3d5d374700c8eb8e2f79831f6e961a7ecdf7ecb4
